### ISSUE TITLE
Oracle module not found

### ISSUE THREAD

**Issue by codemonkeyneo** [strongloop/strong-oracle#22]
I'm trying to connect to oracle for custom route but keep getting 'Cannot find module 'oracle''.

I can connect using Arc and can read from the tables etc great, what I'm trying to do is now call a procedure in oracle (following is in a module.exports section for the app.

'''
app.get('/oracletest', function(req, res) {
    
    var settings = {};
    var oracle = require("oracle")(settings);
 
    var connectData = { "user": "userhere", "password": "passwordhere", "tns": "tnshere" };

    oracle.connect(connectData, function(err, connection) {
      console.log('must have connected woooohoooo');
      connection.close(); // call this when you are done with the connection 
    });

Any help appreciated.

**Comment by raymondfeng** [comment]
The module name is 'strong-oracle' instead of 'oracle'.
