### ISSUE TITLE
setAutoCommit is not working / default is not auto commit

### ISSUE THREAD

**Issue by vschoettke** [strongloop/strong-oracle#27]
2854cfaeec260219be13367d86c2e778360d7aaf commented `stmt->setAutoCommit` out in connection.cpp and reader.cpp and therefore `setAutoCommit(true/false)` is not working anymore.

This is not mentioned in the changelog or documentation so I guess it was done by mistake.

**Comment by raymondfeng** [comment]
Good catch. Fixed and released in 1.6.1.
