### ISSUE TITLE
Support for LONG RAW data type

### ISSUE THREAD

**Issue by pgkehle** [strongloop/strong-oracle#54]
Hello.  I am trying to pull data from a legacy system that uses the LONG RAW data type for one of its columns. It'd be really helpful for this package to support this data type (24).   Oracle ODBC Driver Release 11.2.0.1.0 says that Prefetch for LONG RAW data types is supported.  

https://docs.oracle.com/database/121/ADFNS/adfns_odbc.htm#BABBFBBG

I'm trying to tweak this package manually, but I'm not an expert in developing node packages.  

EDIT: I would post this to the official node-oracledb project, but they have yet to finish upgrading to using NAN2 (so it seems) thus their package does not yet compile to Node v4.2.1.

**Comment by pgkehle** [comment]
I actually have code that is working for my purposes, that I would like to publish to a branch.  It's at least a starting point.

**Comment by raymondfeng** [comment]
Would you like to submit a PR?

**Comment by pgkehle** [comment]
Ideally yes, but first at least push to a branch.

**Comment by pgkehle** [comment]
Can you please give me access to a branch, or let me know how I can send you a few files to do this for me?  I figure there is one tweak in the code you might want to do, to remove a hard-coded value.  But otherwise, pulls from the database seem to work for my purposes.  Thanks.

**Comment by raymondfeng** [comment]
You can folk the repo into your own github account, change the code there, and then submit a pull request. See https://help.github.com/articles/using-pull-requests/

**Comment by pgkehle** [comment]
Got it.  Hadn't done that specific action before (pull request from forked project).  I see someone has already noticed this and commented.  Thank you.

**Comment by pgkehle** [comment]
Marking this closed as the PR has been merged.
