### ISSUE TITLE
Convert node-oracledb connectstring to strong-oracle

### ISSUE THREAD

**Issue by AlaRuba** [strongloop/strong-oracle#58]
Hi,

I couldn't find this in your documentation, but let's say I have the following connection attributes in node-oracledb.

    {
        user          : "hr",
        password      : "welcome",
        connectString : "localhost/XE"
  }

I noticed that strong-oracle connections don't accept a connectString. How do I convert this to a strong-oracle format. I'm not sure database in the strong-oracle connection stands for.

Thanks

**Comment by raymondfeng** [comment]
Use host, port, and database properties.

**Comment by AlaRuba** [comment]
That's it. Thanks.
