### ISSUE TITLE
Silently fails on require

### ISSUE THREAD

**Issue by lebolo** [strongloop/strong-oracle#62]
I recently updated to node v5.7.1 (and npm v3.8.0) and now node crashes silently on `var oracle = require("strong-oracle")({});`

But I can't get a stack trace or anything else. Node just quits when it tries to instantiate the client DB. It was working before on node v5.1.0.

If it helps, the same happens with the oracledb package.

**Comment by raymondfeng** [comment]
Hmm, I just run `npm i` with `strong-oracle` using node `5.7.1` on Mac. The `example/app` works for me. Which OS do you use?

**Comment by lebolo** [comment]
Sorry, that's important =) Windows 7.

**Comment by raymondfeng** [comment]
I'll try later.

**Comment by raymondfeng** [comment]
I just tried on Windows 7 with Node 5.7.1. It works for me the same way as described for MAC.

**Comment by lebolo** [comment]
:cry: Hmm, okay I'll try a fresh installation and `example/app` soon. I'll close this for now and re-open or create a new issue if I find out more. Thanks.
