### ISSUE TITLE
Connection Pool

### ISSUE THREAD

**Issue by stella-di** [strongloop/strong-oracle#64]
I want to create a connection pool to ORACLE with node.js 

```
var oracle = require('strong-oracle')(settings);
var connectionPool;

oracle.createConnectionPool(settings, function (err, pool) {
    if (err) {
        callback(err);
    }

    connectionPool = pool;        
});
```
Can I get the instance of pool using the code below?

```
function getPool(){    
    return connectionPool;
}
```

**Comment by bnoordhuis** [comment]
Yes, but it's going to return `undefined` until the `oracle.createConnectionPool()` callback has run.

**Comment by stella-di** [comment]
Can I get pool object without callback?

**Comment by bnoordhuis** [comment]
@stella-di Did you delete your other comment?

> Can I get pool object without callback? 

Yes, use the synchronous version: `connectionPool = oracle.createConnectionPoolSync(settings)`.  I'll close the issue, I think that answers it, doesn't it?

**Comment by stella-di** [comment]
Yes! It is an answer. Thanks a lot!
